backend:
  name: git-gateway
  repo: gongiskhan/medmulhere
  branch: master

media_folder: "images"

collections:
  - label: "Pages"
    name: "pages"
    files:
      - label: "Home Page"
        name: "index"
        file: "index.html"
        fields:
          - {label: Title, name: title, widget: string}
